apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-wordpress
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/MarioAran/k8s-wordpress
    targetRevision: main
    path: .  # Raíz del repositorio
    directory:
      recurse: true 
  destination:
    server: https://kubernetes.default.svc
    namespace: k8s-wordpress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true