apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: default
type: Opaque
data: 
  root-password: cm9vdHBhc3N3b3JkMTIz   # rootpassword123
  user-password: d3BwYXNzd29yZDEyMw==   # wppassword123 
  database-name: d29yZHByZXNz           # wordpress 
  user-name: d3B1c2Vy                   # wpuser
