apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: default
type: Opaque
data: 
  root-password: cm9vdHBhc3N3b3JkMTIz
  user-password: d3BwYXNzd29yZDEyMw==
  database-name: d29yZHByZXNz
  user-name: d3B1c2Vy
