apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress:latest
        ports:
        - containerPort: 80 
        env:
          - name:  WORDPRESS_DB_HOST
            value: "mysql-service"
          - name: WORDPRESS_DB_NAME
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: database-name
          - name: WORDPRESS_DB_USER
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: user-name
          - name: WORDPRESS_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: user-password
          - name: WP_REDIS_HOST
            value: "redis-service"
          - name: WP_REDIS_PORT
            value: "6379"

        volumeMounts:
        - name:  wordpress-storage
          mountPath:  /var/www/html
      volumes:
      - name: wordpress-storage
        persistentVolumeClaim:
          claimName: wordpress-pvc
      